package com.hackerapps.c2k.data.backup

import com.hackerapps.c2k.data.db.entity.RoutePointEntity
import com.hackerapps.c2k.data.db.entity.WorkoutSessionEntity
import org.json.JSONArray
import org.json.JSONObject

/** A session together with its recorded GPS route, the unit of backup import/export. */
data class SessionWithRoute(
    val session: WorkoutSessionEntity,
    val routePoints: List<RoutePointEntity>
)

/**
 * Versioned JSON backup of workout history. Uses org.json (built into Android) to avoid adding a
 * serialization dependency, matching the app's existing hand-rolled CSV/GPX writers. Route points
 * are nested under their session so the autogenerated row ids never need to be exported.
 */
object HistoryBackup {
    const val FORMAT = "c2k-history"
    const val SCHEMA_VERSION = 1

    fun serialize(data: List<SessionWithRoute>, appVersionCode: Int, exportedAt: Long): String {
        val root = JSONObject()
            .put("format", FORMAT)
            .put("schemaVersion", SCHEMA_VERSION)
            .put("exportedAt", exportedAt)
            .put("appVersionCode", appVersionCode)
        val sessions = JSONArray()
        for (swr in data) {
            val s = swr.session
            val o = JSONObject()
                .put("programId", s.programId)
                .put("week", s.week)
                .put("day", s.day)
                .put("startedAt", s.startedAt)
                .put("durationSeconds", s.durationSeconds)
                .put("distanceMeters", s.distanceMeters.toDouble())
                .put("completed", s.completed)
            if (s.completedAt != null) o.put("completedAt", s.completedAt)
            val pts = JSONArray()
            for (p in swr.routePoints) {
                val po = JSONObject()
                    .put("lat", p.latitude)
                    .put("lon", p.longitude)
                    .put("recordedAt", p.recordedAt)
                if (p.altitudeMeters != null) po.put("alt", p.altitudeMeters)
                if (p.speedMps != null) po.put("speed", p.speedMps.toDouble())
                pts.put(po)
            }
            o.put("routePoints", pts)
            sessions.put(o)
        }
        root.put("sessions", sessions)
        return root.toString(2)
    }

    /**
     * Parses and validates a backup document. Returned sessions have id = 0 and their route points
     * have sessionId = 0; the repository assigns real ids on insert.
     * @throws IllegalArgumentException if the document is not a recognised/supported C2K backup.
     */
    fun parse(text: String): List<SessionWithRoute> {
        val root = try {
            JSONObject(text)
        } catch (e: Exception) {
            throw IllegalArgumentException("Not a valid backup file", e)
        }
        if (root.optString("format") != FORMAT) {
            throw IllegalArgumentException("Not a C2K history backup")
        }
        val version = root.optInt("schemaVersion", -1)
        if (version < 1 || version > SCHEMA_VERSION) {
            throw IllegalArgumentException("Unsupported backup version ($version)")
        }
        val sessionsArr = root.optJSONArray("sessions") ?: JSONArray()
        val out = ArrayList<SessionWithRoute>(sessionsArr.length())
        for (i in 0 until sessionsArr.length()) {
            val o = sessionsArr.getJSONObject(i)
            val session = WorkoutSessionEntity(
                id = 0,
                programId = o.getString("programId"),
                week = o.getInt("week"),
                day = o.getInt("day"),
                startedAt = o.getLong("startedAt"),
                completedAt = if (o.has("completedAt")) o.getLong("completedAt") else null,
                durationSeconds = o.getInt("durationSeconds"),
                distanceMeters = o.optDouble("distanceMeters", 0.0).toFloat(),
                completed = o.optBoolean("completed", false)
            )
            val ptsArr = o.optJSONArray("routePoints") ?: JSONArray()
            val pts = ArrayList<RoutePointEntity>(ptsArr.length())
            for (j in 0 until ptsArr.length()) {
                val po = ptsArr.getJSONObject(j)
                pts.add(
                    RoutePointEntity(
                        id = 0,
                        sessionId = 0,
                        latitude = po.getDouble("lat"),
                        longitude = po.getDouble("lon"),
                        altitudeMeters = if (po.has("alt")) po.getDouble("alt") else null,
                        speedMps = if (po.has("speed")) po.getDouble("speed").toFloat() else null,
                        recordedAt = po.getLong("recordedAt")
                    )
                )
            }
            out.add(SessionWithRoute(session, pts))
        }
        return out
    }
}
